parameters:
#    levi9_e_project.example.class: Levi9\EProjectBundle\Example

services:
#    levi9_e_project.example:
#        class: %levi9_e_project.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
